coincake/app/routes/admin.php
<?php

coincake/app/routes/web.php
        Route::post('/close-market/{id}', 'HomeController@closemarket')->name('closemarket');
        Route::post('/open-market/{id}', 'HomeController@openmarket')->name('openmarket');
        Route::post('/vieworder', 'HomeController@vieworder')->name('view-order');
        Route::get('/vieworder', 'HomeController@vieworder2')->name('vieworder');
        Route::get('/buy-market', 'HomeController@buymarket')->name('buyonmarket');
        Route::post('/buy-market', 'HomeController@buymarketpost')->name('buyonmarketpost');
        Route::get('/coin-market', 'HomeController@coinmarket')->name('coinmarket');
        Route::post('/pay-market', 'HomeController@paymarket')->name('paymarket');
        Route::get('/pay-market', 'HomeController@marketpaypreview')->name('market.paypreview');
        Route::post('/paid-market', 'HomeController@marketpay')->name('marketpaid');
        Route::post('/search-market', 'HomeController@searchmarket')->name('searchmarket');
        Route::post('/search-market-place', 'HomeController@searchmarketplace')->name('searchmarketplace');

        Route::post('/market_paystack', 'PaymentController@marketpaystack')->name('marketpaystack');
        Route::post('/market_rave', 'PaymentController@marketrave')->name('marketrave');
        Route::post('/market_approve/{id}', 'HomeController@approvemarketsale')->name('approvemarketsale');
        Route::post('/market_reject/{id}', 'HomeController@rejectmarketsale')->name('rejectmarketsale');
        Route::post('/market_approve2/{id}', 'HomeController@approvemarketsale2')->name('approvemarketsale2');
        Route::post('/market_reject2/{id}', 'HomeController@rejectmarketsale2')->name('rejectmarketsale2');
        Route::post('/messagebuyer/{id}', 'HomeController@messagebuyer')->name('messagebuyer');
        Route::get('/viewtrx/{id}', 'HomeController@viewtrx')->name('viewtrx');


        Route::post('buy','HomeController@buy')->name('buy.amount');
        Route::get('buy/{trx}','HomeController@buyPreview')->name('buy.buyPreview');
        Route::post('confirm-buy','HomeController@buyConfirm')->name('buy.confirmed');
        Route::post('confirm-buy-slip','HomeController@buyConfirmSlip')->name('buy.confirmed.slip');

        Route::post('sell','HomeController@sell')->name('sell.amount');
        Route::get('sell/{trx}','HomeController@sellPreview')->name('sell.preview');
        Route::post('confirm-sell','HomeController@sellConfirm')->name('sell.confirmed');
        Route::post('confirm-sell-bank','HomeController@sellConfirmBank')->name('sell.confirmed.bank');

        Route::post('exchange/wallet','HomeController@exchangewallet')->name('exchange.wallet');
        Route::post('exchange/online','HomeController@exchangeonline')->name('exchange.online');
        Route::get('exchange','HomeController@exchange')->name('exchange');

        Route::get('transactions','HomeController@transactions')->name('transaction');
    });

});


Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminLoginController@index')->name('admin.loginForm');
    Route::post('/', 'AdminLoginController@authenticate')->name('admin.login');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {



    Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');


    Route::get('/exchange-log', 'AdminController@exchangeLog')->name('exchange-currency');
    Route::get('/exchange-log/{id}', 'AdminController@exchangeInfo')->name('exchange-info');
    Route::get('/exchange-approve/{id}', 'AdminController@exchangeapprove')->name('exchange.approve');
    Route::get('/exchange-reject/{id}', 'AdminController@exchangereject')->name('exchange.reject');
    Route::post('/exchange-action', 'AdminController@exchangeAction')->name('exchange-action');

    Route::get('/sell-log', 'AdminController@sellLog')->name('sell-currency');
    Route::get('/pending-sell-log', 'AdminController@pendingsellLog')->name('pendingsell-currency');
    Route::get('/declined-sell-log', 'AdminController@declinedsellLog')->name('declinedsell-currency');
    Route::get('/sell-log/{id}', 'AdminController@sellInfo')->name('sell-info');
    Route::get('/sell-approve/{id}', 'AdminController@sellapprove')->name('sell.approve');
    Route::get('/sell-reject/{id}', 'AdminController@sellreject')->name('sell.reject');

    Route::get('/buy-log', 'AdminController@buyLog')->name('buy-currency');
    Route::get('/pending-buy-log', 'AdminController@pendingbuyLog')->name('pendingbuy-currency');
    Route::get('/declined-buy-log', 'AdminController@declinedbuyLog')->name('declinedbuy-currency');
    Route::get('/buy-log/{id}', 'AdminController@buyInfo')->name('buy-info');
    Route::get('/buy-app/{id}', 'AdminController@buyapprove')->name('buy.approve');
    Route::get('/buy-rej/{id}', 'AdminController@buyreject')->name('buy.reject');


    // General Settings
    Route::get('/general-settings', 'GeneralSettingController@GenSetting')->name('admin.GenSetting');
    Route::post('/general-settings', 'GeneralSettingController@UpdateGenSetting')->name('admin.UpdateGenSetting');


    // General Settings
    Route::get('/blockchain-settings', 'GeneralSettingController@blockchainSetting')->name('admin.blockchainSetting');
    Route::post('/blockchain-settings', 'GeneralSettingController@UpdateblockchainSetting')->name('admin.UpdateblockchainSetting');

    //Contact Setting
    Route::get('contact-setting', 'GeneralSettingController@getContact')->name('contact-setting');
    Route::put('contact-setting/{id}', 'GeneralSettingController@putContactSetting')->name('contact-setting-update');


    // Admin Settings
    Route::get('/change-password', 'AdminController@changePassword')->name('admin.changePass');
    Route::post('/change-password', 'AdminController@updatePassword')->name('admin.changePass');
    Route::get('/profile', 'AdminController@profile')->name('admin.profile');
    Route::post('/profile', 'AdminController@updateProfile')->name('admin.profile');



        //Blockchain
        Route::get('blockchain/{id}','BlockchainController@blockchainwallet')->name('admin.blockchainwallet');
        Route::get('createwallet/{id}','BlockchainController@createwallet')->name('admin.createwallet');
        Route::get('/wallet/{id}', 'BlockchainController@viewwallets')->name('admin.viewwallet');

        Route::post('/send/coin', 'BlockchainController@sendcoin')->name('admin.sendcoin');
        Route::post('/send/preview', 'BlockchainController@sendpreview')->name('admin.sendpreview');
        Route::get('/wallet-sent/{id}', 'BlockchainController@walletsent')->name('admin.walletsent');
        Route::get('/wallet-received/{id}', 'BlockchainController@walletreceived')->name('admin.walletreceived');
        Route::post('/send/coin', 'BlockchainController@sendcoin')->name('admin.sendcoin');
        Route::get('/block_wallet/{id}', 'BlockchainController@blockwallet')->name('admin.blockwallet');
        Route::get('/unblock_wallet/{id}', 'BlockchainController@unblockwallet')->name('admin.unblockwallet');

 //Offer
 Route::get('/active-market', 'MarketController@activeoffer')->name('activeoffer');
 Route::get('/inactive-market', 'MarketController@inactiveoffer')->name('inactiveoffer');
 Route::get('/activate-market/{id}', 'MarketController@actdeal')->name('actdeal');
 Route::get('/deactivate-market/{id}', 'MarketController@deactdeal')->name('deactdeal');
 Route::get('/delete-market/{id}', 'MarketController@deldeal')->name('deldeal');
 Route::get('/pending-offer', 'MarketController@orderpend')->name('orderpend');
 Route::get('/processed-offer', 'MarketController@orderprocessed')->name('orderprocess');
 Route::get('/rejected-offer', 'MarketController@orderrej')->name('orderrej');
 Route::get('/view-deal/{id}', 'MarketController@viewdeal')->name('viewdeal');
 Route::get('/approved-deal/{id}', 'MarketController@dealapp')->name('dealapp');
 Route::get('/approved-rej/{id}', 'MarketController@dealrej')->name('dealrej');


    Route::resource('currency','CurrencyController');
     Route::get('/activate-coin/{id}', 'CurrencyController@activate')->name('activatecoin');
    Route::get('/deactivate-coin/{id}', 'CurrencyController@deactivate')->name('deactivatecoin');
    Route::get('/delete-coin/{id}', 'CurrencyController@delete')->name('deletecoin');
    Route::post('/post-coin/', 'CurrencyController@post')->name('postcoin');





    //Gateway
    Route::get('/gateway', 'GatewayController@show')->name('gateway');
    Route::get('/actgateway/{id}', 'GatewayController@act')->name('activate.gateway');
    Route::get('/deactgateway/{id}', 'GatewayController@deact')->name('deactivate.gateway');
    Route::post('/gateway', 'GatewayController@update')->name('update.gateway');

    //Deposit
    Route::get('/deposits', 'DepositController@index')->name('deposits');
    Route::get('/deposits/requests', 'DepositController@requests')->name('deposits.requests');
    Route::get('/deposits/declined', 'DepositController@depodec')->name('deposits.declined');
    Route::get('/deposit/approve/{id}', 'DepositController@approve')->name('deposit.approve');
    Route::get('/deposit/view/{id}', 'DepositController@view')->name('deposit.view');
    Route::get('/deposit/{deposit}/delete', 'DepositController@destroy')->name('deposit.destroy');

   //Transfer
    Route::get('/transfer/requests', 'DepositController@transfer')->name('transfer.log');
    Route::get('/transfer/delete/{id}', 'DepositController@transferdelete')->name('transfer.delete');
    Route::get('/transfer/{id}', 'DepositController@transferview')->name('transfer.view');

    //withdraw
    Route::get('/withdraw', 'WithdrawController@index')->name('withdraw');
    Route::post('/withdraw', 'WithdrawController@delete')->name('add.withdraw.method');
    Route::post('/withdraw-update', 'WithdrawController@withdrawUpdateSettings')->name('update.wsettings');

    Route::get('/withdraw/requests', 'WithdrawController@requests')->name('withdraw.requests');

coincake/app/app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Currency extends Model
{

     use SoftDeletes;
    protected $guarded = [];
    protected $table = "currencies";


    public function cryptowallet()
    {
        return $this->hasMany('App\Cryptowallet','id','coin_id');
    }
    public function trx()
    {
        return $this->hasMany('App\Trx','id');
    }
}

coincake/app/app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use Illuminate\Http\Request;
use Auth;
use App\GeneralSettings;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Hash;
use File;
use Image;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_title'] = 'Manage Currency';
        $data['currency'] = Currency::latest()->get();
        return view('admin.currency.index', $data);
    }


    public function delete($id)
    {
        $data = Currency::find($id);
        $data->delete();
        $data->status= 0;
        $data->save();


        $notification =  array('message' => 'Coin Deleted Successfully !!', 'alert-type' => 'success');
        return back()->with($notification);
	}


    public function activate($id)
    {
        $data = Currency::find($id);
        $data->status= 1;
        $data->save();

        $notification =  array('message' => 'Coin Activated Successfully !!', 'alert-type' => 'success');
        return back()->with($notification);
	}


    public function deactivate($id)
    {
        $data = Currency::find($id);
        $data->status= 0;
        $data->save();

        $notification =  array('message' => 'Coin Deactivated Successfully !!', 'alert-type' => 'success');
        return back()->with($notification);
	}


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['page_title'] = 'Manage Currency';
        return view('admin.currency.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'buy' => 'required|min:0',
            'sell' => 'required|min:0',
            'price' => 'required|numeric|min:0',
            'symbol' => 'required',
            'payment_id' => 'required',
            'name' => 'required',
        ]);
        $in = Input::except('_method', '_token');
        $in['is_coin'] = $request->is_coin == "on" ? 1 : 0;
        $in['status'] = $request->status == "on" ? 1 : 0;


        Currency::create($in);
        return back()->with('success', 'Cryptocrrency Created Successfully!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function show(Currency $currency)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function edit(Currency $currency)
    {
        $data['currency'] = $currency;
        $data['page_title'] = "Manage Currency";
        return view('admin.currency.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function post(Request $request )
    {

        $request->validate([
            'buy' => 'required|min:0',
            'payment_id' => 'required',
            'sell' => 'required|min:0',
            'price' => 'required|numeric|min:0',
            'symbol' => 'required',
            'name' => 'required',
        ]);

        $data = Currency::find($request->id);
        $data['name'] = $request->name ;
        $data['symbol'] = $request->symbol ;
        $data['sell'] = $request->sell ;
        $data['buy'] = $request->buy ;
        $data['exchange'] = $request->exchange ;
        $data['price'] = $request->price ;
        $data['payment_id'] = $request->payment_id ;
        $data->save();

        return back()->with('success', 'Currency Updated Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
        //
    }
}

coincake/app/resources/views/admin/currency/buy-info.blade.php
@extends('include.admindashboard')

@section('body')


<script>
function goBack() {
  window.history.back()
}
</script>

   <div class="page-content"><div class="container"><div class="card content-area"><div class="card-innr"><div class="card-head d-flex justify-content-between align-items-center"><h4 class="card-title mb-0">Transaction Details</h4><a href="#" onclick="goBack()" class="btn btn-sm btn-auto btn-primary d-sm-block d-none"><em class="fas fa-arrow-left mr-3"></em>Back</a><a href="#" onclick="goBack()" class="btn btn-icon btn-sm btn-primary d-sm-none"><em class="fas fa-arrow-left"></em></a></div><div class="gaps-1-5x"></div><div class="data-details d-md-flex"><div class="fake-class"><span class="data-details-title">Tranx Date</span><span class="data-details-info">{{date('d M Y',strtotime($exchange->created_at))}}</span></div><div class="fake-class"><span class="data-details-title">Tranx Status</span> @if( $exchange->status ==2 )
                                                <span class="badge badge-success">Success</span>
                                            @elseif( $exchange->status == -2 )
                                                <span class="badge badge-danger">Rejected</span>
                                            @else
                                                <span class="badge badge-warning">Pending</span>
                                            @endif</div><div class="fake-class"><span class="data-details-title">Tranx Time</span><span class="data-details-info"> {{$exchange->created_at}}</span></div></div><div class="gaps-3x"></div><h6 class="card-sub-title">Transaction Info</h6><ul class="data-details-list"><li><div class="data-details-head">Transaction Type</div><div class="data-details-des"><strong>Purchase</strong></div></li><!-- li --><li><div class="data-details-head">Amount</div><div class="data-details-des"><strong>{{number_format($exchange->amount, $basic->decimal)}} USD</strong></div></li><!-- li --><li><div class="data-details-head">Cryptocurrency</div><div class="data-details-des"><strong>{{$exchange->currency->name}}</strong></div></li><!-- li --><li><div class="data-details-head">Amount In {{$basic->currency}}</div><div class="data-details-des"><span>{{$basic->currency_sym}}{{number_format($exchange->main_amo, $basic->decimal)}}</span> <span></span></div></li><!-- li --><li><div class="data-details-head">Transaction ID</div><div class="data-details-des"><span>{{$exchange->trx}} </span> <span></span></div></li><!-- li --><li><div class="data-details-head">Details</div><div class="data-details-des">{{$exchange->remark}}</div></li><!-- li --></ul><!-- .data-details --><div class="gaps-3x"></div><h6 class="card-sub-title">Transaction Details</h6><ul class="data-details-list"><li><div class="data-details-head">Payment Method</div><div class="data-details-des"><strong>
     @if($exchange->gateway)

{{App\Gateway::whereId($exchange->gateway)->first()->name}}

@else
                                            {{App\PaymentMethod::whereId($exchange->method)->first()->name}}
           @endif

                                            </strong></div></li><!-- li --><li>





                                            <div class="data-details-head">Amount Paid</div><div class="data-details-des"><span><strong>{{number_format($exchange->amountpaid , $basic->decimal)}} {{$basic->currency}}</strong>  </span> <span>({{number_format($exchange->amount - $exchange->charge, $basic->decimal)}} {{$basic->currency}} + {{$exchange->currency->buy}}%)</span></div></li><!-- li --><li><div class="data-details-head">TRX Charge</div><div class="data-details-des"><strong>{{number_format($exchange->charge, $basic->decimal)}} {{$basic->currency}} <small> {{$exchange->currency->buy}}%</small></strong></div></li><!-- li --><li><div class="data-details-head">{{$exchange->currency->symbol}} To Receive</div><div class="data-details-des"><span>{{number_format($exchange->getamo, 8)}} {{$exchange->currency->symbol}}</span></div></li><!-- li --><li><div class="data-details-head">Amount To Credit</div><div class="data-details-des"><span>${{$exchange->amount}} worth of {{$exchange->currency->symbol}}</span><span>({{$exchange->currency->name}})</span></div></li><!-- li --><li><div class="data-details-head">Payment To</div><div class="data-details-des"><span><strong>{{$exchange->wallet}}</strong></span></div></li>

@if($exchange->gateway < 1)
<li><div class="data-details-head">Payment Number</div><div class="data-details-des"><span><strong>{{$exchange->tnum}}</strong></span></div></li>

<li><br><div class="data-details-head">Payment Screenshot</div><div class="data-doc-item data-doc-item-lg"><div class="data-doc-image"><img src="{{asset('uploads/payments/'.$exchange->image)}}" alt="passport"></div><ul class="data-doc-actions"><li><a href="{{asset('uploads/payments/'.$exchange->image)}}" download><em class="ti ti-import"></em></a></li></ul></div></li>
@endif
<!-- li --></ul><!-- .data-details --></div></div><!-- .card --></div><!-- .container --></div>
@endsection
@section('script')
@endsection

coincake/app/resources/views/admin/currency/edit.blade.php
@extends('include.admindashboard')

@section('body')
  <div class="page-header"><div class="container"><div class="row justify-content-center"><div class="col-lg-8 col-xl-7 text-center"><h2 class="page-title">View Cryptocurrency</h2></div></div></div><!-- .container --></div><div class="page-content"><div class="container"><div class="row"> <div class="col-lg-12"><div class="content-area card"><div class="card-innr card-innr-fix2"><div class="card-head"><h6 class="card-title">Update Currency</h6></div><div class="gaps-1x"></div><!-- .gaps -->

  <form role="form" method="POST" action="{{route('postcoin' )}}"
     name="editForm" enctype="multipart/form-data">
    {{ csrf_field() }}
  <div class="row">



  <div class="col-xl-6 col-sm-6"><div class="input-item input-with-label"><label class="input-item-label ucap text-exlight">Currency Name</label><input type="text" class="input-bordered"
                                           name="name"        placeholder="Currency Name" value="{{$currency->name}}">
<input hidden name="id" value="{{$currency->id}}">

                                                   </div></div><div class="col-xl-6 col-sm-6"><div class="input-item input-with-label"><label class="input-item-label ucap text-exlight">Currency Symbol</label> <input type="text" class="input-bordered"
                                               placeholder="Currency Symbol" value="{{$currency->symbol}}"
                                               name="symbol"></div></div><div class="col-xl-6 col-sm-6"><div class="input-item input-with-label"><label class="input-item-label ucap text-exlight">Currency Price</label><input type="text" name="price" value="{{$currency->price}}"
                                                  class="input-bordered"
                                                   onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')"></div></div><div class="col-xl-6 col-sm-6"><div class="input-item input-with-label"><label class="input-item-label ucap text-exlight">Wallet Address</label> <input type="text" name="payment_id" value="{{$currency->payment_id}}"
                                               name="payment_id" class="input-bordered"
                                               placeholder="Payment Id"></div></div></div><div class="row"><div class="col-md-6"><div class="input-item input-with-label"><label class="input-item-label ucap text-exlight">Sell Rate</label> <input type="text" name="sell" value="{{$currency->sell}}" class="input-bordered"
                                                   placeholder="0.00"
                                                   ></div></div><div class="col-md-6"><div class="input-item input-with-label"><label class="input-item-label ucap text-exlight">Purchase Rate</label> <input type="text" name="buy" value="{{$currency->buy}}"
                                                   class="input-bordered"
                                                   placeholder="0.00"
                                                   onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')"></div></div></div> </div><!-- .card-innr -->

    <div class="form-group col-md-12 ">
                                        <button class="btn btn-primary btn-lg">Update</button></form>
                                    </div>
</div><!-- .card -->

                                                   </div> </div><!-- .card-innr --></div><!-- .card --></div></div></div><!-- .container --></div>
@stop

coincake/app/resources/views/admin/currency/index.blade.php
@extends('include.admindashboard')

@section('body')
    <div class="page-content"><div class="container"><div class="card content-area"><div class="card-innr"><div class="card-head"><h4 class="card-title">Cryptocurrency List</h4></div><table class="data-table dt-init user-list"><thead><tr class="data-item data-head"><th class="data-col dt-user">Name</th><th class="data-col dt-email">Address</th><th class="data-col dt-token">Rate</th>  <th class="data-col dt-status"><div class="dt-status-text">Status</div></th><th class="data-col"></th></tr></thead><tbody>
<a href="#" data-toggle="modal" data-target="#createcoin" class="btn btn-sm btn-primary btn-outline"><em class="ti ti-trash"></em> Create New</a>
 @foreach($currency as $k=>$data)
<tr class="data-item"><td class="data-col dt-user"><span class="lead user-name">{{$data->name }}</span><span class="sub user-id"></span></td><td class="data-col dt-email"><span class="sub sub-s2 sub-email">{{$data->payment_id}}</span></td><td class="data-col dt-token"><span class="lead lead-btoken">1 USD =
    {{$data->price}} {{$data->symbol}}</span></td>

<td class="data-col dt-status">

@if($data->status == 1)
<span class="dt-status-md badge badge-outline badge-success badge-md">Active</span>
<span class="dt-status-sm badge badge-sq badge-outline badge-success badge-md">A</span>
@else
<span class="dt-status-md badge badge-outline badge-danger badge-md">Inactive</span>
<span class="dt-status-sm badge badge-sq badge-outline badge-danger badge-md">I</span>
@endif

</td><td class="data-col text-right"><div class="relative d-inline-block"><a href="#" class="btn btn-light-alt btn-xs btn-icon toggle-tigger"><em class="ti ti-more-alt"></em></a><div class="toggle-class dropdown-content dropdown-content-top-left"><ul class="dropdown-list"><li><a href="{{route('currency.edit',$data->id)}}"><em class="ti ti-eye"></em> View Details</a></li><li><a href="{{route('activatecoin',$data->id)}}"><em class="ti ti-check"></em> Activate</a></li>
<li><a href="{{route('deactivatecoin',$data->id)}}"><em class="ti ti-na"></em> Deactivate</a></li>

<li><a href="{{route('deletecoin',$data->id)}}"><em class="ti ti-trash"></em> Delete</a></li></ul></div></div></td></tr>
@endforeach

<!-- .data-item --></tbody></table></div><!-- .card-innr --></div><!-- .card --></div><!-- .container --></div><!-- .page-content -->





<!-- .modal-dialog --></div><!-- Modal End --><div class="modal fade" id="createcoin" tabindex="-1"><div class="modal-dialog modal-dialog-md modal-dialog-centered"><div class="modal-content"><div class="popup-body"><h4 class="popup-title">Create New Currency</h4> <p>Fill the form below to create a new cryptocurrency for the system. Please note that the currency symbol has to conform with the standart blockchain currency symbol. Please check <a href="https://min-api.cryptocompare.com">Here</a> to see list of supported currency symbols.</p>

<div class="input-item input-with-label">

<form role="form" method="POST" action="{{route('currency.store')}}" name="editForm" enctype="multipart/form-data">
                                {{ csrf_field() }}

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label class="input-item-label text-exlight">Currency  Name:</label>
                                        <div class="input-group">
                                            <input type="text" class="input-bordered" placeholder="Currency  Name" value="{{old('name')}}"
                                                   name="name">

                                        </div>

                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="input-item-label text-exlight"> Currency 	Symbol:</label>
                                        <input type="text"class="input-bordered"  placeholder="Currency Symbol" value="{{old('symbol')}}"
                                               name="symbol">


                                    </div>

                                </div>
                                <div class="row">

                                    <div class="form-group col-md-12">
                                        <label class="input-item-label text-exlight">Price:</label>
                                        <div class="input-group">

                                            <input type="text" name="price"  value="{{old('price')}}" class="input-bordered"
                                                   onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">
                                        </div>

                                    </div>





                                    <div class="form-group col-md-12">
                                        <label class="input-item-label text-exlight"> Payment Wallet</label>
                                            <input type="text" name="payment_id"  value="{{old('payment_id')}}" class="input-bordered"
                                                   placeholder="Payment Wallet Address" >

                                    </div>





                                    <div class="form-group col-md-6">
                                        <label class="input-item-label text-exlight"> Buying Rate</label>
                                        <div class="input-group">
                                            <input type="text" name="buy" value="{{old('buy')}}" class="input-bordered"
                                                   placeholder="0.00" onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">

                                        </div>

                                    </div>

                                    <div class="form-group col-md-6">
                                        <label class="input-item-label text-exlight"> Selling Rate</label>
                                        <div class="input-group">
                                            <input type="text" name="sell"  value="{{old('sell')}}" class="input-bordered"
                                                   placeholder="0.00" onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">


                                        </div>

                                    </div>
                                </div>




                            </div><!-- .input-item --><ul class="d-flex flex-wrap align-items-center guttar-30px"><li><button type="submit" class="btn btn-primary">Create Currency</button></form></li><li class="pdt-1x pdb-1x"><a href="#" data-dismiss="modal" data-toggle="modal" data-target="#pay-online" class="link link-primary">Cancel</a></li></ul><div class="gaps-2x"></div><div class="gaps-1x d-none d-sm-block"></div></div></div><!-- .modal-content --></div><!-- .modal-dialog --></div><!-- Modal End -->
@endsection